version: '3.8'

services:
  web:
    build: ./django_project
    restart: always
    command: sh -c "python manage.py migrate && python manage.py createsuperuser --noinput && gunicorn django_project.wsgi:application --bind 0.0.0.0:8000"
    environment:
      - DJANGO_SUPERUSER_USERNAME=arty
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
    volumes:
      - ./django_project/:/usr/src/django_project/
      - ./django_project/static/:/usr/src/django_project/static/
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_user
      - POSTGRES_DB=django_dev
  nginx:
    build: ./nginx
    ports:
      - "8089:80"
    volumes:
      - ./django_project/static/:/usr/src/django_project/static/
    depends_on:
      - web

volumes:
  postgres_db:
  local_volume:
